// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: department.proto

package com.dimageshare.core.autogen.grpc.department;

public interface DepartmentIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:department.DepartmentIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 dpId = 1;</code>
   */
  int getDpId();
}
