// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: department.proto

package com.dimageshare.core.autogen.grpc.department;

public interface DepartmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:department.Department)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 dpId = 1;</code>
   */
  int getDpId();

  /**
   * <code>string dpName = 2;</code>
   */
  java.lang.String getDpName();
  /**
   * <code>string dpName = 2;</code>
   */
  com.google.protobuf.ByteString
      getDpNameBytes();

  /**
   * <code>string dpDescription = 3;</code>
   */
  java.lang.String getDpDescription();
  /**
   * <code>string dpDescription = 3;</code>
   */
  com.google.protobuf.ByteString
      getDpDescriptionBytes();
}
