---
server:
  port: ${HTTP_SERVER_PORT:5555}
  context-path: /api

grpc:
#  server:
#    port: ${GRPC_SERVER_PORT:59090}
  client:
    channels:
      user:
        hosts:
        - ${GRPC_MASTER_HOST:localhost}
        ports:
        - ${GRPC_MASTER_PORT:55593}

logging:
  level: debug, info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %m%n"

security:
  basic:
    enabled: false
