# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: department.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='department.proto',
  package='department',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10\x64\x65partment.proto\x12\ndepartment\x1a\x1bgoogle/protobuf/empty.proto\"D\n\nDepartment\x12\r\n\x05\x64p_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x64p_name\x18\x02 \x01(\t\x12\x16\n\x0e\x64p_description\x18\x03 \x01(\t\";\n\x10\x44\x65partmentSaving\x12\x0f\n\x07\x64p_name\x18\x01 \x01(\t\x12\x16\n\x0e\x64p_description\x18\x02 \x01(\t\"$\n\x13\x44\x65partmentIdRequest\x12\r\n\x05\x64p_id\x18\x01 \x01(\x05\"A\n\x13\x44\x65partmentResponses\x12*\n\ndepartment\x18\x01 \x03(\x0b\x32\x16.department.Department2\xcf\x02\n\x11\x44\x65partmentService\x12K\n\x10\x66ind_departments\x12\x16.google.protobuf.Empty\x1a\x1f.department.DepartmentResponses\x12P\n\x15\x66ind_department_by_id\x12\x1f.department.DepartmentIdRequest\x1a\x16.department.Department\x12G\n\x0fsave_department\x12\x1c.department.DepartmentSaving\x1a\x16.google.protobuf.Empty\x12R\n\x17remove_department_by_id\x12\x1f.department.DepartmentIdRequest\x1a\x16.google.protobuf.Emptyb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_DEPARTMENT = _descriptor.Descriptor(
  name='Department',
  full_name='department.Department',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dp_id', full_name='department.Department.dp_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dp_name', full_name='department.Department.dp_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dp_description', full_name='department.Department.dp_description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=129,
)


_DEPARTMENTSAVING = _descriptor.Descriptor(
  name='DepartmentSaving',
  full_name='department.DepartmentSaving',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dp_name', full_name='department.DepartmentSaving.dp_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dp_description', full_name='department.DepartmentSaving.dp_description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=190,
)


_DEPARTMENTIDREQUEST = _descriptor.Descriptor(
  name='DepartmentIdRequest',
  full_name='department.DepartmentIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dp_id', full_name='department.DepartmentIdRequest.dp_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=228,
)


_DEPARTMENTRESPONSES = _descriptor.Descriptor(
  name='DepartmentResponses',
  full_name='department.DepartmentResponses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='department', full_name='department.DepartmentResponses.department', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=295,
)

_DEPARTMENTRESPONSES.fields_by_name['department'].message_type = _DEPARTMENT
DESCRIPTOR.message_types_by_name['Department'] = _DEPARTMENT
DESCRIPTOR.message_types_by_name['DepartmentSaving'] = _DEPARTMENTSAVING
DESCRIPTOR.message_types_by_name['DepartmentIdRequest'] = _DEPARTMENTIDREQUEST
DESCRIPTOR.message_types_by_name['DepartmentResponses'] = _DEPARTMENTRESPONSES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Department = _reflection.GeneratedProtocolMessageType('Department', (_message.Message,), {
  'DESCRIPTOR' : _DEPARTMENT,
  '__module__' : 'department_pb2'
  # @@protoc_insertion_point(class_scope:department.Department)
  })
_sym_db.RegisterMessage(Department)

DepartmentSaving = _reflection.GeneratedProtocolMessageType('DepartmentSaving', (_message.Message,), {
  'DESCRIPTOR' : _DEPARTMENTSAVING,
  '__module__' : 'department_pb2'
  # @@protoc_insertion_point(class_scope:department.DepartmentSaving)
  })
_sym_db.RegisterMessage(DepartmentSaving)

DepartmentIdRequest = _reflection.GeneratedProtocolMessageType('DepartmentIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEPARTMENTIDREQUEST,
  '__module__' : 'department_pb2'
  # @@protoc_insertion_point(class_scope:department.DepartmentIdRequest)
  })
_sym_db.RegisterMessage(DepartmentIdRequest)

DepartmentResponses = _reflection.GeneratedProtocolMessageType('DepartmentResponses', (_message.Message,), {
  'DESCRIPTOR' : _DEPARTMENTRESPONSES,
  '__module__' : 'department_pb2'
  # @@protoc_insertion_point(class_scope:department.DepartmentResponses)
  })
_sym_db.RegisterMessage(DepartmentResponses)



_DEPARTMENTSERVICE = _descriptor.ServiceDescriptor(
  name='DepartmentService',
  full_name='department.DepartmentService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=298,
  serialized_end=633,
  methods=[
  _descriptor.MethodDescriptor(
    name='find_departments',
    full_name='department.DepartmentService.find_departments',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_DEPARTMENTRESPONSES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='find_department_by_id',
    full_name='department.DepartmentService.find_department_by_id',
    index=1,
    containing_service=None,
    input_type=_DEPARTMENTIDREQUEST,
    output_type=_DEPARTMENT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='save_department',
    full_name='department.DepartmentService.save_department',
    index=2,
    containing_service=None,
    input_type=_DEPARTMENTSAVING,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='remove_department_by_id',
    full_name='department.DepartmentService.remove_department_by_id',
    index=3,
    containing_service=None,
    input_type=_DEPARTMENTIDREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEPARTMENTSERVICE)

DESCRIPTOR.services_by_name['DepartmentService'] = _DEPARTMENTSERVICE

# @@protoc_insertion_point(module_scope)
