// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: department.proto

package com.dimageshare.protobuf.core.autogen.grpc.department;

public interface DepartmentByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:department.DepartmentByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
