// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package demo.protobuf.core.autogen.grpc.user;

public interface FetchUserByDepartmentIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.FetchUserByDepartmentIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 departmentId = 1;</code>
   */
  int getDepartmentId();
}
