// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package demo.protobuf.core.autogen.grpc.user;

public interface FetchUserByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.FetchUserByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
