// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package demo.protobuf.core.autogen.grpc.user;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_FetchUserByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_FetchUserByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_UserResponses_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_UserResponses_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_FetchUserByDepartmentIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_FetchUserByDepartmentIdRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\004user\032\033google/protobuf/empt" +
      "y.proto\"j\n\004User\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(" +
      "\t\022\026\n\003sex\030\003 \001(\0162\t.user.Sex\022\r\n\005email\030\004 \001(\t" +
      "\022\013\n\003age\030\005 \001(\005\022\024\n\014departmentId\030\006 \001(\005\"\"\n\024F" +
      "etchUserByIdRequest\022\n\n\002id\030\001 \001(\005\")\n\rUserR" +
      "esponses\022\030\n\004user\030\001 \003(\0132\n.user.User\"6\n\036Fe" +
      "tchUserByDepartmentIdRequest\022\024\n\014departme" +
      "ntId\030\001 \001(\005*&\n\003Sex\022\010\n\004MALE\020\000\022\n\n\006FEMALE\020\001\022" +
      "\t\n\005OTHER\020\0022\327\001\n\013UserService\0229\n\nfetchUsers" +
      "\022\026.google.protobuf.Empty\032\023.user.UserResp" +
      "onses\0227\n\rfetchUserById\022\032.user.FetchUserB" +
      "yIdRequest\032\n.user.User\022T\n\027fetchUserByDep" +
      "artmentId\022$.user.FetchUserByDepartmentId" +
      "Request\032\023.user.UserResponsesB(\n$demo.pro" +
      "tobuf.core.autogen.grpc.userP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_user_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Sex", "Email", "Age", "DepartmentId", });
    internal_static_user_FetchUserByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_FetchUserByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_FetchUserByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_user_UserResponses_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_user_UserResponses_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_UserResponses_descriptor,
        new java.lang.String[] { "User", });
    internal_static_user_FetchUserByDepartmentIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_user_FetchUserByDepartmentIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_FetchUserByDepartmentIdRequest_descriptor,
        new java.lang.String[] { "DepartmentId", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
