---
grpc:
  server:
    port: ${GRPC_SERVER_PORT:52061}

security:
  basic:
    enabled: false
region:
  prefecture: files/region-prefecture.xlsx

industryType:
  mrjobtype: files/mrjobtype.xlsx
