// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: department.proto

package demo.protobuf.core.autogen.grpc.department;

public final class DepartmentOuterClass {
  private DepartmentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_department_Department_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_department_Department_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_department_FetchDepartmentByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_department_FetchDepartmentByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_department_DepartmentResponses_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_department_DepartmentResponses_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020department.proto\022\ndepartment\032\033google/p" +
      "rotobuf/empty.proto\";\n\nDepartment\022\n\n\002id\030" +
      "\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003 \001(\t" +
      "\"(\n\032FetchDepartmentByIdRequest\022\n\n\002id\030\001 \001" +
      "(\005\"A\n\023DepartmentResponses\022*\n\ndepartment\030" +
      "\001 \003(\0132\026.department.Department2\245\001\n\013UserSe" +
      "rvice\022E\n\nfetchUsers\022\026.google.protobuf.Em" +
      "pty\032\037.department.DepartmentResponses\022O\n\r" +
      "fetchUserById\022&.department.FetchDepartme" +
      "ntByIdRequest\032\026.department.DepartmentB.\n" +
      "*configuration.protobuf.core.autogen.grpc.departm" +
      "entP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_department_Department_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_department_Department_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_department_Department_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", });
    internal_static_department_FetchDepartmentByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_department_FetchDepartmentByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_department_FetchDepartmentByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_department_DepartmentResponses_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_department_DepartmentResponses_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_department_DepartmentResponses_descriptor,
        new java.lang.String[] { "Department", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
