// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: department.proto

package demo.protobuf.core.autogen.grpc.department;

public interface FetchDepartmentByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:department.FetchDepartmentByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
