#Config db
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

max-age: 3600

#Config for tomcat
server:
  port: 5593
  tomcat:
    max-threads: 200
  servlet:
    context-path: /api