---
spring:
  data:
    mongodb:
      repositories:
        enabled: true
      uri: mongodb://localhost:27017/unittest
region:
  prefecture: files/region-prefecture-test.xlsx

industryType:
  mrjobtype: files/mrjobtype-test.xlsx