// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: department.proto

package com.dimageshare.core.autogen.grpc.department;

/**
 * Protobuf type {@code department.DepartmentSaving}
 */
public  final class DepartmentSaving extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:department.DepartmentSaving)
    DepartmentSavingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DepartmentSaving.newBuilder() to construct.
  private DepartmentSaving(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DepartmentSaving() {
    dpName_ = "";
    dpDescription_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DepartmentSaving(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            dpName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            dpDescription_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dimageshare.core.autogen.grpc.department.DepartmentOuterClass.internal_static_department_DepartmentSaving_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dimageshare.core.autogen.grpc.department.DepartmentOuterClass.internal_static_department_DepartmentSaving_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dimageshare.core.autogen.grpc.department.DepartmentSaving.class, com.dimageshare.core.autogen.grpc.department.DepartmentSaving.Builder.class);
  }

  public static final int DPNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object dpName_;
  /**
   * <code>string dpName = 1;</code>
   */
  public java.lang.String getDpName() {
    java.lang.Object ref = dpName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dpName_ = s;
      return s;
    }
  }
  /**
   * <code>string dpName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDpNameBytes() {
    java.lang.Object ref = dpName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dpName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DPDESCRIPTION_FIELD_NUMBER = 2;
  private volatile java.lang.Object dpDescription_;
  /**
   * <code>string dpDescription = 2;</code>
   */
  public java.lang.String getDpDescription() {
    java.lang.Object ref = dpDescription_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dpDescription_ = s;
      return s;
    }
  }
  /**
   * <code>string dpDescription = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDpDescriptionBytes() {
    java.lang.Object ref = dpDescription_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dpDescription_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDpNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dpName_);
    }
    if (!getDpDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dpDescription_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDpNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dpName_);
    }
    if (!getDpDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dpDescription_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dimageshare.core.autogen.grpc.department.DepartmentSaving)) {
      return super.equals(obj);
    }
    com.dimageshare.core.autogen.grpc.department.DepartmentSaving other = (com.dimageshare.core.autogen.grpc.department.DepartmentSaving) obj;

    boolean result = true;
    result = result && getDpName()
        .equals(other.getDpName());
    result = result && getDpDescription()
        .equals(other.getDpDescription());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DPNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDpName().hashCode();
    hash = (37 * hash) + DPDESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDpDescription().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dimageshare.core.autogen.grpc.department.DepartmentSaving parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentSaving parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentSaving parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentSaving parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentSaving parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentSaving parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentSaving parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentSaving parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentSaving parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentSaving parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentSaving parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentSaving parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dimageshare.core.autogen.grpc.department.DepartmentSaving prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code department.DepartmentSaving}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:department.DepartmentSaving)
      com.dimageshare.core.autogen.grpc.department.DepartmentSavingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dimageshare.core.autogen.grpc.department.DepartmentOuterClass.internal_static_department_DepartmentSaving_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dimageshare.core.autogen.grpc.department.DepartmentOuterClass.internal_static_department_DepartmentSaving_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dimageshare.core.autogen.grpc.department.DepartmentSaving.class, com.dimageshare.core.autogen.grpc.department.DepartmentSaving.Builder.class);
    }

    // Construct using com.dimageshare.core.autogen.grpc.department.DepartmentSaving.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      dpName_ = "";

      dpDescription_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dimageshare.core.autogen.grpc.department.DepartmentOuterClass.internal_static_department_DepartmentSaving_descriptor;
    }

    public com.dimageshare.core.autogen.grpc.department.DepartmentSaving getDefaultInstanceForType() {
      return com.dimageshare.core.autogen.grpc.department.DepartmentSaving.getDefaultInstance();
    }

    public com.dimageshare.core.autogen.grpc.department.DepartmentSaving build() {
      com.dimageshare.core.autogen.grpc.department.DepartmentSaving result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dimageshare.core.autogen.grpc.department.DepartmentSaving buildPartial() {
      com.dimageshare.core.autogen.grpc.department.DepartmentSaving result = new com.dimageshare.core.autogen.grpc.department.DepartmentSaving(this);
      result.dpName_ = dpName_;
      result.dpDescription_ = dpDescription_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dimageshare.core.autogen.grpc.department.DepartmentSaving) {
        return mergeFrom((com.dimageshare.core.autogen.grpc.department.DepartmentSaving)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dimageshare.core.autogen.grpc.department.DepartmentSaving other) {
      if (other == com.dimageshare.core.autogen.grpc.department.DepartmentSaving.getDefaultInstance()) return this;
      if (!other.getDpName().isEmpty()) {
        dpName_ = other.dpName_;
        onChanged();
      }
      if (!other.getDpDescription().isEmpty()) {
        dpDescription_ = other.dpDescription_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dimageshare.core.autogen.grpc.department.DepartmentSaving parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dimageshare.core.autogen.grpc.department.DepartmentSaving) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object dpName_ = "";
    /**
     * <code>string dpName = 1;</code>
     */
    public java.lang.String getDpName() {
      java.lang.Object ref = dpName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dpName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dpName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDpNameBytes() {
      java.lang.Object ref = dpName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dpName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dpName = 1;</code>
     */
    public Builder setDpName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dpName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dpName = 1;</code>
     */
    public Builder clearDpName() {
      
      dpName_ = getDefaultInstance().getDpName();
      onChanged();
      return this;
    }
    /**
     * <code>string dpName = 1;</code>
     */
    public Builder setDpNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dpName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dpDescription_ = "";
    /**
     * <code>string dpDescription = 2;</code>
     */
    public java.lang.String getDpDescription() {
      java.lang.Object ref = dpDescription_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dpDescription_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dpDescription = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDpDescriptionBytes() {
      java.lang.Object ref = dpDescription_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dpDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dpDescription = 2;</code>
     */
    public Builder setDpDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dpDescription_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dpDescription = 2;</code>
     */
    public Builder clearDpDescription() {
      
      dpDescription_ = getDefaultInstance().getDpDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string dpDescription = 2;</code>
     */
    public Builder setDpDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dpDescription_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:department.DepartmentSaving)
  }

  // @@protoc_insertion_point(class_scope:department.DepartmentSaving)
  private static final com.dimageshare.core.autogen.grpc.department.DepartmentSaving DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dimageshare.core.autogen.grpc.department.DepartmentSaving();
  }

  public static com.dimageshare.core.autogen.grpc.department.DepartmentSaving getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DepartmentSaving>
      PARSER = new com.google.protobuf.AbstractParser<DepartmentSaving>() {
    public DepartmentSaving parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DepartmentSaving(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DepartmentSaving> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DepartmentSaving> getParserForType() {
    return PARSER;
  }

  public com.dimageshare.core.autogen.grpc.department.DepartmentSaving getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

