// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: department.proto

package com.dimageshare.core.autogen.grpc.department;

/**
 * Protobuf type {@code department.DepartmentResponses}
 */
public  final class DepartmentResponses extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:department.DepartmentResponses)
    DepartmentResponsesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DepartmentResponses.newBuilder() to construct.
  private DepartmentResponses(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DepartmentResponses() {
    department_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DepartmentResponses(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              department_ = new java.util.ArrayList<com.dimageshare.core.autogen.grpc.department.Department>();
              mutable_bitField0_ |= 0x00000001;
            }
            department_.add(
                input.readMessage(com.dimageshare.core.autogen.grpc.department.Department.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        department_ = java.util.Collections.unmodifiableList(department_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dimageshare.core.autogen.grpc.department.DepartmentOuterClass.internal_static_department_DepartmentResponses_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dimageshare.core.autogen.grpc.department.DepartmentOuterClass.internal_static_department_DepartmentResponses_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dimageshare.core.autogen.grpc.department.DepartmentResponses.class, com.dimageshare.core.autogen.grpc.department.DepartmentResponses.Builder.class);
  }

  public static final int DEPARTMENT_FIELD_NUMBER = 1;
  private java.util.List<com.dimageshare.core.autogen.grpc.department.Department> department_;
  /**
   * <code>repeated .department.Department department = 1;</code>
   */
  public java.util.List<com.dimageshare.core.autogen.grpc.department.Department> getDepartmentList() {
    return department_;
  }
  /**
   * <code>repeated .department.Department department = 1;</code>
   */
  public java.util.List<? extends com.dimageshare.core.autogen.grpc.department.DepartmentOrBuilder> 
      getDepartmentOrBuilderList() {
    return department_;
  }
  /**
   * <code>repeated .department.Department department = 1;</code>
   */
  public int getDepartmentCount() {
    return department_.size();
  }
  /**
   * <code>repeated .department.Department department = 1;</code>
   */
  public com.dimageshare.core.autogen.grpc.department.Department getDepartment(int index) {
    return department_.get(index);
  }
  /**
   * <code>repeated .department.Department department = 1;</code>
   */
  public com.dimageshare.core.autogen.grpc.department.DepartmentOrBuilder getDepartmentOrBuilder(
      int index) {
    return department_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < department_.size(); i++) {
      output.writeMessage(1, department_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < department_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, department_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dimageshare.core.autogen.grpc.department.DepartmentResponses)) {
      return super.equals(obj);
    }
    com.dimageshare.core.autogen.grpc.department.DepartmentResponses other = (com.dimageshare.core.autogen.grpc.department.DepartmentResponses) obj;

    boolean result = true;
    result = result && getDepartmentList()
        .equals(other.getDepartmentList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDepartmentCount() > 0) {
      hash = (37 * hash) + DEPARTMENT_FIELD_NUMBER;
      hash = (53 * hash) + getDepartmentList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dimageshare.core.autogen.grpc.department.DepartmentResponses parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentResponses parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentResponses parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentResponses parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentResponses parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentResponses parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentResponses parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentResponses parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentResponses parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentResponses parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentResponses parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dimageshare.core.autogen.grpc.department.DepartmentResponses parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dimageshare.core.autogen.grpc.department.DepartmentResponses prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code department.DepartmentResponses}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:department.DepartmentResponses)
      com.dimageshare.core.autogen.grpc.department.DepartmentResponsesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dimageshare.core.autogen.grpc.department.DepartmentOuterClass.internal_static_department_DepartmentResponses_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dimageshare.core.autogen.grpc.department.DepartmentOuterClass.internal_static_department_DepartmentResponses_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dimageshare.core.autogen.grpc.department.DepartmentResponses.class, com.dimageshare.core.autogen.grpc.department.DepartmentResponses.Builder.class);
    }

    // Construct using com.dimageshare.core.autogen.grpc.department.DepartmentResponses.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDepartmentFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (departmentBuilder_ == null) {
        department_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        departmentBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dimageshare.core.autogen.grpc.department.DepartmentOuterClass.internal_static_department_DepartmentResponses_descriptor;
    }

    public com.dimageshare.core.autogen.grpc.department.DepartmentResponses getDefaultInstanceForType() {
      return com.dimageshare.core.autogen.grpc.department.DepartmentResponses.getDefaultInstance();
    }

    public com.dimageshare.core.autogen.grpc.department.DepartmentResponses build() {
      com.dimageshare.core.autogen.grpc.department.DepartmentResponses result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dimageshare.core.autogen.grpc.department.DepartmentResponses buildPartial() {
      com.dimageshare.core.autogen.grpc.department.DepartmentResponses result = new com.dimageshare.core.autogen.grpc.department.DepartmentResponses(this);
      int from_bitField0_ = bitField0_;
      if (departmentBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          department_ = java.util.Collections.unmodifiableList(department_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.department_ = department_;
      } else {
        result.department_ = departmentBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dimageshare.core.autogen.grpc.department.DepartmentResponses) {
        return mergeFrom((com.dimageshare.core.autogen.grpc.department.DepartmentResponses)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dimageshare.core.autogen.grpc.department.DepartmentResponses other) {
      if (other == com.dimageshare.core.autogen.grpc.department.DepartmentResponses.getDefaultInstance()) return this;
      if (departmentBuilder_ == null) {
        if (!other.department_.isEmpty()) {
          if (department_.isEmpty()) {
            department_ = other.department_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDepartmentIsMutable();
            department_.addAll(other.department_);
          }
          onChanged();
        }
      } else {
        if (!other.department_.isEmpty()) {
          if (departmentBuilder_.isEmpty()) {
            departmentBuilder_.dispose();
            departmentBuilder_ = null;
            department_ = other.department_;
            bitField0_ = (bitField0_ & ~0x00000001);
            departmentBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDepartmentFieldBuilder() : null;
          } else {
            departmentBuilder_.addAllMessages(other.department_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dimageshare.core.autogen.grpc.department.DepartmentResponses parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dimageshare.core.autogen.grpc.department.DepartmentResponses) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.dimageshare.core.autogen.grpc.department.Department> department_ =
      java.util.Collections.emptyList();
    private void ensureDepartmentIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        department_ = new java.util.ArrayList<com.dimageshare.core.autogen.grpc.department.Department>(department_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dimageshare.core.autogen.grpc.department.Department, com.dimageshare.core.autogen.grpc.department.Department.Builder, com.dimageshare.core.autogen.grpc.department.DepartmentOrBuilder> departmentBuilder_;

    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public java.util.List<com.dimageshare.core.autogen.grpc.department.Department> getDepartmentList() {
      if (departmentBuilder_ == null) {
        return java.util.Collections.unmodifiableList(department_);
      } else {
        return departmentBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public int getDepartmentCount() {
      if (departmentBuilder_ == null) {
        return department_.size();
      } else {
        return departmentBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public com.dimageshare.core.autogen.grpc.department.Department getDepartment(int index) {
      if (departmentBuilder_ == null) {
        return department_.get(index);
      } else {
        return departmentBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public Builder setDepartment(
        int index, com.dimageshare.core.autogen.grpc.department.Department value) {
      if (departmentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDepartmentIsMutable();
        department_.set(index, value);
        onChanged();
      } else {
        departmentBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public Builder setDepartment(
        int index, com.dimageshare.core.autogen.grpc.department.Department.Builder builderForValue) {
      if (departmentBuilder_ == null) {
        ensureDepartmentIsMutable();
        department_.set(index, builderForValue.build());
        onChanged();
      } else {
        departmentBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public Builder addDepartment(com.dimageshare.core.autogen.grpc.department.Department value) {
      if (departmentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDepartmentIsMutable();
        department_.add(value);
        onChanged();
      } else {
        departmentBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public Builder addDepartment(
        int index, com.dimageshare.core.autogen.grpc.department.Department value) {
      if (departmentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDepartmentIsMutable();
        department_.add(index, value);
        onChanged();
      } else {
        departmentBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public Builder addDepartment(
        com.dimageshare.core.autogen.grpc.department.Department.Builder builderForValue) {
      if (departmentBuilder_ == null) {
        ensureDepartmentIsMutable();
        department_.add(builderForValue.build());
        onChanged();
      } else {
        departmentBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public Builder addDepartment(
        int index, com.dimageshare.core.autogen.grpc.department.Department.Builder builderForValue) {
      if (departmentBuilder_ == null) {
        ensureDepartmentIsMutable();
        department_.add(index, builderForValue.build());
        onChanged();
      } else {
        departmentBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public Builder addAllDepartment(
        java.lang.Iterable<? extends com.dimageshare.core.autogen.grpc.department.Department> values) {
      if (departmentBuilder_ == null) {
        ensureDepartmentIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, department_);
        onChanged();
      } else {
        departmentBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public Builder clearDepartment() {
      if (departmentBuilder_ == null) {
        department_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        departmentBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public Builder removeDepartment(int index) {
      if (departmentBuilder_ == null) {
        ensureDepartmentIsMutable();
        department_.remove(index);
        onChanged();
      } else {
        departmentBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public com.dimageshare.core.autogen.grpc.department.Department.Builder getDepartmentBuilder(
        int index) {
      return getDepartmentFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public com.dimageshare.core.autogen.grpc.department.DepartmentOrBuilder getDepartmentOrBuilder(
        int index) {
      if (departmentBuilder_ == null) {
        return department_.get(index);  } else {
        return departmentBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public java.util.List<? extends com.dimageshare.core.autogen.grpc.department.DepartmentOrBuilder> 
         getDepartmentOrBuilderList() {
      if (departmentBuilder_ != null) {
        return departmentBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(department_);
      }
    }
    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public com.dimageshare.core.autogen.grpc.department.Department.Builder addDepartmentBuilder() {
      return getDepartmentFieldBuilder().addBuilder(
          com.dimageshare.core.autogen.grpc.department.Department.getDefaultInstance());
    }
    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public com.dimageshare.core.autogen.grpc.department.Department.Builder addDepartmentBuilder(
        int index) {
      return getDepartmentFieldBuilder().addBuilder(
          index, com.dimageshare.core.autogen.grpc.department.Department.getDefaultInstance());
    }
    /**
     * <code>repeated .department.Department department = 1;</code>
     */
    public java.util.List<com.dimageshare.core.autogen.grpc.department.Department.Builder> 
         getDepartmentBuilderList() {
      return getDepartmentFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dimageshare.core.autogen.grpc.department.Department, com.dimageshare.core.autogen.grpc.department.Department.Builder, com.dimageshare.core.autogen.grpc.department.DepartmentOrBuilder> 
        getDepartmentFieldBuilder() {
      if (departmentBuilder_ == null) {
        departmentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dimageshare.core.autogen.grpc.department.Department, com.dimageshare.core.autogen.grpc.department.Department.Builder, com.dimageshare.core.autogen.grpc.department.DepartmentOrBuilder>(
                department_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        department_ = null;
      }
      return departmentBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:department.DepartmentResponses)
  }

  // @@protoc_insertion_point(class_scope:department.DepartmentResponses)
  private static final com.dimageshare.core.autogen.grpc.department.DepartmentResponses DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dimageshare.core.autogen.grpc.department.DepartmentResponses();
  }

  public static com.dimageshare.core.autogen.grpc.department.DepartmentResponses getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DepartmentResponses>
      PARSER = new com.google.protobuf.AbstractParser<DepartmentResponses>() {
    public DepartmentResponses parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DepartmentResponses(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DepartmentResponses> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DepartmentResponses> getParserForType() {
    return PARSER;
  }

  public com.dimageshare.core.autogen.grpc.department.DepartmentResponses getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

