// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: department.proto

package com.dimageshare.core.autogen.grpc.department;

public interface DepartmentSavingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:department.DepartmentSaving)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dpName = 1;</code>
   */
  java.lang.String getDpName();
  /**
   * <code>string dpName = 1;</code>
   */
  com.google.protobuf.ByteString
      getDpNameBytes();

  /**
   * <code>string dpDescription = 2;</code>
   */
  java.lang.String getDpDescription();
  /**
   * <code>string dpDescription = 2;</code>
   */
  com.google.protobuf.ByteString
      getDpDescriptionBytes();
}
