# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='user.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\nuser.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x82\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x17\n\x06gender\x18\x03 \x01(\x0e\x32\x07.Gender\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x0b\n\x03\x61ge\x18\x05 \x01(\x05\x12\x14\n\x0cphone_number\x18\x06 \x01(\t\x12\x15\n\rdepartment_id\x18\x07 \x01(\x05\"|\n\nUserSaving\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x06gender\x18\x02 \x01(\x0e\x32\x07.Gender\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\x14\n\x0cphone_number\x18\x05 \x01(\t\x12\x15\n\rdepartment_id\x18\x06 \x01(\x05\"\x1b\n\rUserIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"$\n\rUserResponses\x12\x13\n\x04user\x18\x01 \x03(\x0b\x32\x05.User\",\n\x13\x44\x65partmentIdRequest\x12\x15\n\rdepartment_id\x18\x01 \x01(\x05*)\n\x06Gender\x12\x08\n\x04MALE\x10\x00\x12\n\n\x06\x46\x45MALE\x10\x01\x12\t\n\x05OTHER\x10\x02\x32\xa0\x02\n\x0bUserService\x12\x34\n\nfind_users\x12\x16.google.protobuf.Empty\x1a\x0e.UserResponses\x12(\n\x0f\x66ind_user_by_id\x12\x0e.UserIdRequest\x1a\x05.User\x12\x42\n\x1a\x66ind_user_by_department_id\x12\x14.DepartmentIdRequest\x1a\x0e.UserResponses\x12\x30\n\tsave_user\x12\x0b.UserSaving\x1a\x16.google.protobuf.Empty\x12;\n\x11remove_user_by_id\x12\x0e.UserIdRequest\x1a\x16.google.protobuf.Emptyb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])

_GENDER = _descriptor.EnumDescriptor(
  name='Gender',
  full_name='Gender',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MALE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=415,
  serialized_end=456,
)
_sym_db.RegisterEnumDescriptor(_GENDER)

Gender = enum_type_wrapper.EnumTypeWrapper(_GENDER)
MALE = 0
FEMALE = 1
OTHER = 2



_USER = _descriptor.Descriptor(
  name='User',
  full_name='User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='User.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='User.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='User.gender', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='User.email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='User.age', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phone_number', full_name='User.phone_number', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='department_id', full_name='User.department_id', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=174,
)


_USERSAVING = _descriptor.Descriptor(
  name='UserSaving',
  full_name='UserSaving',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='UserSaving.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='UserSaving.gender', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='UserSaving.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='UserSaving.age', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phone_number', full_name='UserSaving.phone_number', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='department_id', full_name='UserSaving.department_id', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=300,
)


_USERIDREQUEST = _descriptor.Descriptor(
  name='UserIdRequest',
  full_name='UserIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UserIdRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=329,
)


_USERRESPONSES = _descriptor.Descriptor(
  name='UserResponses',
  full_name='UserResponses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='UserResponses.user', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=367,
)


_DEPARTMENTIDREQUEST = _descriptor.Descriptor(
  name='DepartmentIdRequest',
  full_name='DepartmentIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='department_id', full_name='DepartmentIdRequest.department_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=413,
)

_USER.fields_by_name['gender'].enum_type = _GENDER
_USERSAVING.fields_by_name['gender'].enum_type = _GENDER
_USERRESPONSES.fields_by_name['user'].message_type = _USER
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['UserSaving'] = _USERSAVING
DESCRIPTOR.message_types_by_name['UserIdRequest'] = _USERIDREQUEST
DESCRIPTOR.message_types_by_name['UserResponses'] = _USERRESPONSES
DESCRIPTOR.message_types_by_name['DepartmentIdRequest'] = _DEPARTMENTIDREQUEST
DESCRIPTOR.enum_types_by_name['Gender'] = _GENDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)

UserSaving = _reflection.GeneratedProtocolMessageType('UserSaving', (_message.Message,), {
  'DESCRIPTOR' : _USERSAVING,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UserSaving)
  })
_sym_db.RegisterMessage(UserSaving)

UserIdRequest = _reflection.GeneratedProtocolMessageType('UserIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERIDREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UserIdRequest)
  })
_sym_db.RegisterMessage(UserIdRequest)

UserResponses = _reflection.GeneratedProtocolMessageType('UserResponses', (_message.Message,), {
  'DESCRIPTOR' : _USERRESPONSES,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UserResponses)
  })
_sym_db.RegisterMessage(UserResponses)

DepartmentIdRequest = _reflection.GeneratedProtocolMessageType('DepartmentIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEPARTMENTIDREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:DepartmentIdRequest)
  })
_sym_db.RegisterMessage(DepartmentIdRequest)



_USERSERVICE = _descriptor.ServiceDescriptor(
  name='UserService',
  full_name='UserService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=459,
  serialized_end=747,
  methods=[
  _descriptor.MethodDescriptor(
    name='find_users',
    full_name='UserService.find_users',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_USERRESPONSES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='find_user_by_id',
    full_name='UserService.find_user_by_id',
    index=1,
    containing_service=None,
    input_type=_USERIDREQUEST,
    output_type=_USER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='find_user_by_department_id',
    full_name='UserService.find_user_by_department_id',
    index=2,
    containing_service=None,
    input_type=_DEPARTMENTIDREQUEST,
    output_type=_USERRESPONSES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='save_user',
    full_name='UserService.save_user',
    index=3,
    containing_service=None,
    input_type=_USERSAVING,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='remove_user_by_id',
    full_name='UserService.remove_user_by_id',
    index=4,
    containing_service=None,
    input_type=_USERIDREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSERVICE)

DESCRIPTOR.services_by_name['UserService'] = _USERSERVICE

# @@protoc_insertion_point(module_scope)
