#Config db
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

max-age: 3600

#Config grpc client
grpc:
  client:
    channels:
      master:
        hosts:
          - ${GRPC_MASTER_HOST:localhost}
        ports:
          - ${GRPC_MASTER_PORT:55993}

#Config for tomcat
server:
  port: 5593
  tomcat:
    max-threads: 200
  servlet:
    context-path: /api