server:
  port: ${HTTP_SERVER_PORT:5555}
  context-path: /api

grpc:
#  server:
#    port: ${GRPC_SERVER_PORT:56789}
  client:
    channels:
      user:
        hosts:
          - ${GRPC_MASTER_HOST:localhost}
        ports:
          - ${GRPC_MASTER_PORT:55593}
      department:
        hosts:
          - ${GRPC_MASTER_HOST:localhost}
        ports:
          - ${GRPC_MASTER_PORT:11994}

#Config db
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

max-age: 3000

logging:
  level: debug, info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %m%n"

security:
  basic:
    enabled: false
