// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.dimageshare.core.autogen.grpc.user;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_UserSaving_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_UserSaving_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_UserIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_UserIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_UserResponses_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_UserResponses_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_DepartmentIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_DepartmentIdRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\004user\032\033google/protobuf/empt" +
      "y.proto\032\037google/protobuf/timestamp.proto" +
      "\"\205\001\n\004User\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\034\n\006g" +
      "ender\030\003 \001(\0162\014.user.Gender\022\r\n\005email\030\004 \001(\t" +
      "\022\013\n\003age\030\005 \001(\005\022\023\n\013phoneNumber\030\006 \001(\t\022\024\n\014de" +
      "partmentId\030\007 \001(\005\"\177\n\nUserSaving\022\014\n\004name\030\001" +
      " \001(\t\022\034\n\006gender\030\002 \001(\0162\014.user.Gender\022\r\n\005em" +
      "ail\030\003 \001(\t\022\013\n\003age\030\004 \001(\005\022\023\n\013phoneNumber\030\005 " +
      "\001(\t\022\024\n\014departmentId\030\006 \001(\005\"\033\n\rUserIdReque" +
      "st\022\n\n\002id\030\001 \001(\005\")\n\rUserResponses\022\030\n\004user\030" +
      "\001 \003(\0132\n.user.User\"+\n\023DepartmentIdRequest" +
      "\022\024\n\014departmentId\030\001 \001(\005*)\n\006Gender\022\010\n\004MALE" +
      "\020\000\022\n\n\006FEMALE\020\001\022\t\n\005OTHER\020\0022\267\002\n\013UserServic" +
      "e\0228\n\tfindUsers\022\026.google.protobuf.Empty\032\023" +
      ".user.UserResponses\022/\n\014findUserById\022\023.us" +
      "er.UserIdRequest\032\n.user.User\022H\n\026findUser" +
      "ByDepartmentId\022\031.user.DepartmentIdReques" +
      "t\032\023.user.UserResponses\0224\n\010saveUser\022\020.use" +
      "r.UserSaving\032\026.google.protobuf.Empty\022=\n\016" +
      "removeUserById\022\023.user.UserIdRequest\032\026.go" +
      "ogle.protobuf.EmptyB*\n&com.dimageshare.c" +
      "ore.autogen.grpc.userP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_user_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Gender", "Email", "Age", "PhoneNumber", "DepartmentId", });
    internal_static_user_UserSaving_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_UserSaving_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_UserSaving_descriptor,
        new java.lang.String[] { "Name", "Gender", "Email", "Age", "PhoneNumber", "DepartmentId", });
    internal_static_user_UserIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_user_UserIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_UserIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_user_UserResponses_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_user_UserResponses_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_UserResponses_descriptor,
        new java.lang.String[] { "User", });
    internal_static_user_DepartmentIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_user_DepartmentIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_DepartmentIdRequest_descriptor,
        new java.lang.String[] { "DepartmentId", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
