server:
  port: ${HTTP_SERVER_PORT:5593}
  context-path: /api

grpc:
  client:
    channels:
      user:
        hosts:
          - ${GRPC_MASTER_HOST:localhost}
        ports:
          - ${GRPC_MASTER_PORT:55993}
      department:
        hosts:
          - ${GRPC_MASTER_HOST:localhost}
          - ${GRPC_MASTER_PORT:11994}

logging:
  level: debug, info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %m%n"

security:
  basic:
    enabled: false