// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: department.proto

package com.dimageshare.protobuf.core.autogen.grpc.user;

public interface DepartmentIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:department.DepartmentIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 departmentId = 1;</code>
   */
  int getDepartmentId();
}
