// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: department.proto

package com.dimageshare.protobuf.core.autogen.grpc.user;

public interface UserResponsesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:department.UserResponses)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .department.User department = 1;</code>
   */
  java.util.List<com.dimageshare.protobuf.core.autogen.grpc.user.User> 
      getUserList();
  /**
   * <code>repeated .department.User department = 1;</code>
   */
  com.dimageshare.protobuf.core.autogen.grpc.user.User getUser(int index);
  /**
   * <code>repeated .department.User department = 1;</code>
   */
  int getUserCount();
  /**
   * <code>repeated .department.User department = 1;</code>
   */
  java.util.List<? extends com.dimageshare.protobuf.core.autogen.grpc.user.UserOrBuilder> 
      getUserOrBuilderList();
  /**
   * <code>repeated .department.User department = 1;</code>
   */
  com.dimageshare.protobuf.core.autogen.grpc.user.UserOrBuilder getUserOrBuilder(
      int index);
}
