# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import com.entropy.user.grpc.user_pb2 as user__pb2


class UserServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.find_users = channel.unary_unary(
        '/UserService/find_users',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=user__pb2.UserResponses.FromString,
        )
    self.find_user_by_id = channel.unary_unary(
        '/UserService/find_user_by_id',
        request_serializer=user__pb2.UserIdRequest.SerializeToString,
        response_deserializer=user__pb2.User.FromString,
        )
    self.find_user_by_department_id = channel.unary_unary(
        '/UserService/find_user_by_department_id',
        request_serializer=user__pb2.DepartmentIdRequest.SerializeToString,
        response_deserializer=user__pb2.UserResponses.FromString,
        )
    self.save_user = channel.unary_unary(
        '/UserService/save_user',
        request_serializer=user__pb2.UserSaving.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.remove_user_by_id = channel.unary_unary(
        '/UserService/remove_user_by_id',
        request_serializer=user__pb2.UserIdRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class UserServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def find_users(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def find_user_by_id(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def find_user_by_department_id(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def save_user(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def remove_user_by_id(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'find_users': grpc.unary_unary_rpc_method_handler(
          servicer.find_users,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=user__pb2.UserResponses.SerializeToString,
      ),
      'find_user_by_id': grpc.unary_unary_rpc_method_handler(
          servicer.find_user_by_id,
          request_deserializer=user__pb2.UserIdRequest.FromString,
          response_serializer=user__pb2.User.SerializeToString,
      ),
      'find_user_by_department_id': grpc.unary_unary_rpc_method_handler(
          servicer.find_user_by_department_id,
          request_deserializer=user__pb2.DepartmentIdRequest.FromString,
          response_serializer=user__pb2.UserResponses.SerializeToString,
      ),
      'save_user': grpc.unary_unary_rpc_method_handler(
          servicer.save_user,
          request_deserializer=user__pb2.UserSaving.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'remove_user_by_id': grpc.unary_unary_rpc_method_handler(
          servicer.remove_user_by_id,
          request_deserializer=user__pb2.UserIdRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'UserService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
