// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.dimageshare.core.autogen.grpc.user;

public interface GetSumResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.GetSumResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sum = 1;</code>
   */
  int getSum();
}
