// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.dimageshare.core.autogen.grpc.user;

/**
 * Protobuf type {@code user.GetSumResponse}
 */
public  final class GetSumResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:user.GetSumResponse)
    GetSumResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetSumResponse.newBuilder() to construct.
  private GetSumResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetSumResponse() {
    sum_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetSumResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            sum_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dimageshare.core.autogen.grpc.user.UserOuterClass.internal_static_user_GetSumResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dimageshare.core.autogen.grpc.user.UserOuterClass.internal_static_user_GetSumResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dimageshare.core.autogen.grpc.user.GetSumResponse.class, com.dimageshare.core.autogen.grpc.user.GetSumResponse.Builder.class);
  }

  public static final int SUM_FIELD_NUMBER = 1;
  private int sum_;
  /**
   * <code>int32 sum = 1;</code>
   */
  public int getSum() {
    return sum_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sum_ != 0) {
      output.writeInt32(1, sum_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, sum_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dimageshare.core.autogen.grpc.user.GetSumResponse)) {
      return super.equals(obj);
    }
    com.dimageshare.core.autogen.grpc.user.GetSumResponse other = (com.dimageshare.core.autogen.grpc.user.GetSumResponse) obj;

    boolean result = true;
    result = result && (getSum()
        == other.getSum());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUM_FIELD_NUMBER;
    hash = (53 * hash) + getSum();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dimageshare.core.autogen.grpc.user.GetSumResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dimageshare.core.autogen.grpc.user.GetSumResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dimageshare.core.autogen.grpc.user.GetSumResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dimageshare.core.autogen.grpc.user.GetSumResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dimageshare.core.autogen.grpc.user.GetSumResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dimageshare.core.autogen.grpc.user.GetSumResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dimageshare.core.autogen.grpc.user.GetSumResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dimageshare.core.autogen.grpc.user.GetSumResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dimageshare.core.autogen.grpc.user.GetSumResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dimageshare.core.autogen.grpc.user.GetSumResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dimageshare.core.autogen.grpc.user.GetSumResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dimageshare.core.autogen.grpc.user.GetSumResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dimageshare.core.autogen.grpc.user.GetSumResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code user.GetSumResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:user.GetSumResponse)
      com.dimageshare.core.autogen.grpc.user.GetSumResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dimageshare.core.autogen.grpc.user.UserOuterClass.internal_static_user_GetSumResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dimageshare.core.autogen.grpc.user.UserOuterClass.internal_static_user_GetSumResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dimageshare.core.autogen.grpc.user.GetSumResponse.class, com.dimageshare.core.autogen.grpc.user.GetSumResponse.Builder.class);
    }

    // Construct using com.dimageshare.core.autogen.grpc.user.GetSumResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      sum_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dimageshare.core.autogen.grpc.user.UserOuterClass.internal_static_user_GetSumResponse_descriptor;
    }

    public com.dimageshare.core.autogen.grpc.user.GetSumResponse getDefaultInstanceForType() {
      return com.dimageshare.core.autogen.grpc.user.GetSumResponse.getDefaultInstance();
    }

    public com.dimageshare.core.autogen.grpc.user.GetSumResponse build() {
      com.dimageshare.core.autogen.grpc.user.GetSumResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dimageshare.core.autogen.grpc.user.GetSumResponse buildPartial() {
      com.dimageshare.core.autogen.grpc.user.GetSumResponse result = new com.dimageshare.core.autogen.grpc.user.GetSumResponse(this);
      result.sum_ = sum_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dimageshare.core.autogen.grpc.user.GetSumResponse) {
        return mergeFrom((com.dimageshare.core.autogen.grpc.user.GetSumResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dimageshare.core.autogen.grpc.user.GetSumResponse other) {
      if (other == com.dimageshare.core.autogen.grpc.user.GetSumResponse.getDefaultInstance()) return this;
      if (other.getSum() != 0) {
        setSum(other.getSum());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dimageshare.core.autogen.grpc.user.GetSumResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dimageshare.core.autogen.grpc.user.GetSumResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int sum_ ;
    /**
     * <code>int32 sum = 1;</code>
     */
    public int getSum() {
      return sum_;
    }
    /**
     * <code>int32 sum = 1;</code>
     */
    public Builder setSum(int value) {
      
      sum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sum = 1;</code>
     */
    public Builder clearSum() {
      
      sum_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:user.GetSumResponse)
  }

  // @@protoc_insertion_point(class_scope:user.GetSumResponse)
  private static final com.dimageshare.core.autogen.grpc.user.GetSumResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dimageshare.core.autogen.grpc.user.GetSumResponse();
  }

  public static com.dimageshare.core.autogen.grpc.user.GetSumResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetSumResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetSumResponse>() {
    public GetSumResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetSumResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetSumResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetSumResponse> getParserForType() {
    return PARSER;
  }

  public com.dimageshare.core.autogen.grpc.user.GetSumResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

