// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.dimageshare.core.autogen.grpc.user;

public interface GetSumRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.GetSumRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 a = 1;</code>
   */
  int getA();

  /**
   * <code>int32 b = 2;</code>
   */
  int getB();
}
