// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.dimageshare.core.autogen.grpc.user;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_GetSumRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_GetSumRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_GetSumResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_GetSumResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\004user\032\033google/protobuf/empt" +
      "y.proto\032\037google/protobuf/timestamp.proto" +
      "\"%\n\rGetSumRequest\022\t\n\001a\030\001 \001(\005\022\t\n\001b\030\002 \001(\005\"" +
      "\035\n\016GetSumResponse\022\013\n\003sum\030\001 \001(\0052;\n\004User\0223" +
      "\n\006GetSum\022\023.user.GetSumRequest\032\024.user.Get" +
      "SumResponseB*\n&com.dimageshare.core.auto" +
      "gen.grpc.userP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_user_GetSumRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_GetSumRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_GetSumRequest_descriptor,
        new java.lang.String[] { "A", "B", });
    internal_static_user_GetSumResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_GetSumResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_GetSumResponse_descriptor,
        new java.lang.String[] { "Sum", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
